// <auto-generated />
using MicroRabbit.Transfer.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace MicroRabbit.Transfer.Data.Migrations
{
	[DbContext(typeof(TransferDbContext))]
	[Migration("20210609145849_InitialMigration")]
	partial class InitialMigration
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
					.HasAnnotation("Relational:MaxIdentifierLength", 128)
					.HasAnnotation("ProductVersion", "5.0.7")
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

			modelBuilder.Entity("MicroRabbit.Transfer.Domain.Models.TransferLog", b =>
					{
						b.Property<int>("Id")
											.ValueGeneratedOnAdd()
											.HasColumnType("int")
											.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

						b.Property<decimal>("Account")
											.HasColumnType("decimal(18,2)");

						b.Property<string>("FromAccount")
											.HasColumnType("nvarchar(max)");

						b.Property<string>("ToAccount")
											.HasColumnType("nvarchar(max)");

						b.HasKey("Id");

						b.ToTable("TransfersLog");
					});
#pragma warning restore 612, 618
		}
	}
}
